blogs/urls.py
from blogs.apps import BlogsConfig
from django.urls import path

from blogs.views import (
    BlogPostListView,
    BlogPostDetailView,
    BlogPostCreateView,
    BlogPostUpdateView,
    BlogPostDeleteView,
)

app_name = BlogsConfig.name


urlpatterns = [
    path("", BlogPostListView.as_view(), name="blog_list"),
    path("blog_detail/<int:pk>/", BlogPostDetailView.as_view(), name="blog_detail"),
    path("create/", BlogPostCreateView.as_view(), name="blog_create"),
    path("update/<int:pk>/", BlogPostUpdateView.as_view(), name="blog_update"),
    path("delete/<int:pk>/", BlogPostDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from config import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blogs/", include("blogs.urls", namespace="blogs")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models


# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(
        max_length=255,
        verbose_name="Заголовок поста",
        help_text="Введите заголовок поста",
    )
    content = models.TextField(
        verbose_name="Содержание поста", help_text="Введите содержание поста"
    )
    preview_image = models.ImageField(
        upload_to="blog_posts/preview_images", verbose_name="Превью изображение поста"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    publication_sign = models.BooleanField(
        default=False, verbose_name="Публикация поста", help_text="Опубликовать пост?"
    )
    count_views = models.PositiveIntegerField(
        default=0,
        verbose_name="Количество просмотров",
        help_text="Укажите количество просмотров поста",
    )

    class Meta:
        verbose_name = "Блог пост"
        verbose_name_plural = "Блог посты"
        ordering = ["-created_at"]

    def __str__(self):
        return self.title

blogs/forms.py
from django.forms import ModelForm
from django import forms

from blogs.models import BlogPost


class BlogPostForm(ModelForm):
    class Meta:
        model = BlogPost
        fields = ["title", "content", "preview_image", "publication_sign"]
        widgets = {
            "title": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Введите заголовок поста",
                }
            ),
            "content": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Введите содержание поста",
                }
            ),
            "preview_image": forms.FileInput(attrs={"class": "form-control-file"}),
            "publication_sign": forms.CheckboxInput(
                attrs={"class": "form-check-input"}
            ),
        }

blogs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from blogs.forms import BlogPostForm
from blogs.models import BlogPost


class BlogPostListView(ListView):
    model = BlogPost
    template_name = "blogs/blog_list.html"
    context_object_name = "blog_posts"

    def get_queryset(self):
        return BlogPost.objects.filter(publication_sign=True)


class BlogPostDetailView(LoginRequiredMixin, DetailView):
    model = BlogPost
    template_name = "blogs/blog_detail.html"
    context_object_name = "blog_post"

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.count_views += 1
        obj.save()
        return obj


class BlogPostCreateView(LoginRequiredMixin, CreateView):
    model = BlogPost
    template_name = "blogs/blog_create.html"
    form_class = BlogPostForm
    success_url = reverse_lazy("blogs:blog_list")


class BlogPostUpdateView(LoginRequiredMixin, UpdateView):
    model = BlogPost
    template_name = "blogs/blog_create.html"
    form_class = BlogPostForm
    success_url = reverse_lazy("blogs:blog_list")

    def get_success_url(self):
        return reverse("blogs:blog_detail", args=[self.kwargs["pk"]])


class BlogPostDeleteView(LoginRequiredMixin, DeleteView):
    model = BlogPost
    template_name = "blogs/blog_delete.html"
    success_url = reverse_lazy("blogs:blog_list")

blogs/templates/blogs/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}SkyBlog{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
{% include 'blogs/header.html' %}
    <div class="container mt-4">
        {% block content %}{% endblock %}
    </div>
{% include 'blogs/footer.html' %}

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

blogs/templates/blogs/blog_card.html
<div class="col-md-3 d-flex align-items-stretch">
    <div class="card mb-4 shadow-sm">
        <div class="card-header text-center">
            <h4 class="my-0">{{ blog.title }}</h4>
        </div>
        <div class="card-body d-flex flex-column align-items-center">
            <div class="card-body text-center">
                <img src="{{ blog.preview_image.url }}" alt="{{ blog.title }}" class="img-fluid"
                     style="max-width: 70%;">
                <ul class="list-unstyled mt-3 mb-4 text-start flex-grow-1">
                    <li>{{ blog.content|truncatewords:20 }}</li>
                </ul>
            </div>
            <a class="btn btn-primary" href="{% url 'blogs:blog_detail' blog.pk %}">Подробнее</a>
        <a class="btn btn-secondary mt-2" href="{% url 'blogs:blog_update' blog.pk %}">Редактировать</a>
        <a class="btn btn-danger mt-2" href="{% url 'blogs:blog_delete' blog.pk %}">Удалить</a>
        </div>

    </div>
</div>

blogs/templates/blogs/blog_create.html
{% extends 'blogs/base.html' %}
{% load my_tags %}
{% block content %}
<h1>Добавление поста</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.title }}<br>
    {{ form.content }}<br>
    {{ form.preview_image }}<br>
    <span>Опубликовать пост? </span>
    {{ form.publication_sign }}<br>
    <button type="submit" class="btn btn-primary mt-3">
        {% if object %}
            Сохранить
        {% else %}
            Создать
        {% endif %}
    </button>
    {% if form.errors %}
    <div class="alert alert-danger">
        <ul>
            {% for field, errors in form.errors.items %}
            {% for error in errors %}
            <li>{{ field }}: {{ error }}</li>
            {% endfor %}
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    <span class="text-danger mt-3">{{ error }}</span>
</form>
{% endblock %}

blogs/templates/blogs/blog_delete.html
{% extends 'blogs/base.html' %}
{% load my_tags %}
{% block content %}
<h1>Удаление поста</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card-header">
        <p class="card-text">Действительно хотите удалить пост: </p>
        <p class="card-text">{{ object.title }}</p>
    </div>
    <div class="card-body">
        <button type="submit" class="btn btn-danger mt-3">Удалить</button>
        <a class="btn btn-primary mt-3" href="{% url 'blogs:blog_list' %}">Назад</a>
    </div>

    {% if form.errors %}
    <div class="alert alert-danger">
        <ul>
            {% for field, errors in form.errors.items %}
            {% for error in errors %}
            <li>{{ field }}: {{ error }}</li>
            {% endfor %}
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    <span class="text-danger mt-3">{{ error }}</span>
</form>
{% endblock %}

blogs/templates/blogs/blog_detail.html
{% extends 'blogs/base.html' %}
{% block title %}{{ blog_post.title }} - SkyBlog{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="card shadow-sm">
        <div class="card-header text-center">
            <h4 class="my-0">{{ blog_post.title }}</h4>
        </div>
        <div class="card-body text-center">
            <img src="{{ blog_post.preview_image.url }}" class="img-fluid" style="max-width: 400px;">
            <p class="mt-3">{{ blog_post.content }}</p>
            <p class="text-primary">{{ blog_post.count_views }} просмотров</p>
            <a class="btn btn-primary" href="{% url 'blogs:blog_list' %}">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

blogs/templates/blogs/blog_list.html
{% extends 'blogs/base.html' %}
{% block title %}Список блогов - SkyBlog{% endblock %}
{% block content %}
    <div class="text-center">
        <h1 class="display-4">SkyBlog</h1>
        <p class="lead">Отличное место для хранения ваших блогов.</p>
    </div>
    <div class="row justify-content-center text-center">
        {% for blog in blog_posts %}
            {% include 'blogs/blog_card.html' %}
        {% endfor %}
    </div>
{% endblock %}

blogs/templates/blogs/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyBlog
            <small class="d-block mb-3 text-muted">&copy; 2025</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

blogs/templates/blogs/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark align-items-center">
    <div class="container">
        <div class="ms-">
        <a class="navbar-brand py-2" href="{% url 'blogs:blog_list' %}">SkyBlog</a>
        <a class="navbar-brand p-2" href="{% url 'blogs:blog_list' %}">Главная</a>
        <a class="navbar-brand p-2" href="{% url 'blogs:blog_create' %}">Создать пост</a>
        </div>
    </div>
</nav>