blogs/urls.py
from blogs.apps import BlogsConfig
from django.urls import path

from blogs.views import (
    BlogPostListView,
    BlogPostDetailView,
    BlogPostCreateView,
    BlogPostUpdateView,
    BlogPostDeleteView,
)

app_name = BlogsConfig.name


urlpatterns = [
    path("", BlogPostListView.as_view(), name="blog_list"),
    path("blog_detail/<int:pk>/", BlogPostDetailView.as_view(), name="blog_detail"),
    path("create/", BlogPostCreateView.as_view(), name="blog_create"),
    path("update/<int:pk>/", BlogPostUpdateView.as_view(), name="blog_update"),
    path("delete/<int:pk>/", BlogPostDeleteView.as_view(), name="blog_delete"),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import (
    ProductListView,
    ProductDetailView,
    ContactsView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView, ProductsByCategoryView,
)

app_name = CatalogConfig.name

urlpatterns = [
    path("", ProductListView.as_view(), name="product_list"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path(
        "products/product_detail/<int:pk>",cache_page(60)(ProductDetailView.as_view()),
        name="product_detail",
    ),
    path(
        "products/update_product/<int:pk>",
        ProductUpdateView.as_view(),
        name="update_product",
    ),
    path(
        "products/delete_product/<int:pk>",
        ProductDeleteView.as_view(),
        name="product_delete",
    ),
    path("product_category_list/<int:category_id>/", ProductsByCategoryView.as_view(), name="product_category_list"),

    path("contacts/", ContactsView.as_view(), name="contacts"),
]

config/urls.py
from config import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blogs/", include("blogs.urls", namespace="blogs")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig

from users.views import RegisterView

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
]

catalog/models.py
from django.db import models

from users.models import User


class Category(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Название категории",
        help_text="Введите название категории",
    )
    description = models.TextField(
        verbose_name="Описание категории",
        help_text="Введите описание категории",
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Product(models.Model):
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        verbose_name="Владелец продукта",
        blank=True,
        null=True,
    )
    name = models.CharField(
        max_length=100,
        verbose_name="Название продукта",
        help_text="Введите название продукта",
    )
    description = models.TextField(
        verbose_name="Описание продукта",
        help_text="Введите описание продукта",
        blank=True,
        null=True,
    )
    image = models.ImageField(
        upload_to="products/photo",
        blank=True,
        null=True,
        help_text="Загрузите изображение продукта",
        verbose_name="Изображение",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        verbose_name="Категория",
        null=True,
        blank=True,
        related_name="products",
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")
    status = models.BooleanField(default=False, verbose_name="Статус публикации")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"

        permissions = [
            ("can_unpublish_product", "Can unpublish product"),
        ]


class ContactInfo(models.Model):
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return f"Contact Info - {self.address}"


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=15, blank=True, null=True)
    message = models.TextField(default="")

    def __str__(self):
        return self.name

catalog/forms.py
from .models import Product
from django.forms import ModelForm
from django.core.exceptions import ValidationError

bad_words = [
    "казино",
    "криптовалюта",
    "крипта",
    "биржа",
    "дешево",
    "бесплатно",
    "обман",
    "полиция",
    "радар",
]


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["category", "name", "description", "price", "image"]

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields["category"].widget.attrs.update({"class": "form-control"})
        self.fields["name"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите название"}
        )
        self.fields["description"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите описание"}
        )
        self.fields["price"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите цену"}
        )
        self.fields["image"].widget.attrs.update({"class": "form-control"})

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if any(word in name.lower() for word in bad_words):
            raise ValidationError("Название не должно содержать запрещенные слова.")
        return name

    def clean_description(self):
        description = self.cleaned_data.get("description")
        if any(word in description.lower() for word in bad_words):
            raise ValidationError("Название не должно содержать запрещенные слова.")
        return description

    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price < 0:
            raise ValidationError("Неверная цена")
        return price

    def clean_image(self):
        image = self.cleaned_data.get("image")
        if image:
            if image.size > 5 * 1024 * 1025:
                raise ValidationError("Файл больше 5МБ")
            if not (
                image.name.endswith(".jpg")
                or image.name.endswith(".jpeg")
                or image.name.endswith(".png")
            ):
                raise ValidationError("Файл недопустимого формата")
        return image


class ProductModeratorForm(ModelForm):
    class Meta:
        model = Product
        fields = ("status",)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    TemplateView,
    CreateView,
    DeleteView,
    UpdateView,
)

from catalog.forms import ProductForm, ProductModeratorForm
from catalog.models import Product, Contact, Category
from catalog.services import get_products_from_cache, ProductService


class ProductListView(ListView):
    model = Product
    template_name = "catalog/product_list.html"

    def get_queryset(self):
        return get_products_from_cache()


class ProductsByCategoryView(ListView):
    model = Category
    template_name = "catalog/product_category_list.html"
    context_object_name = "categories"

    def get_queryset(self):
        category_id = self.kwargs.get('category_id')
        return ProductService.get_products_from_category(category_id=category_id)


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_update.html"
    success_url = reverse_lazy("catalog:product_list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_update.html"
    success_url = reverse_lazy("catalog:product_list")

    def get_form_class(self):
        """Возвращает форму в зависимости от прав пользователя."""
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm("catalog.can_unpublish_product"):
            return ProductModeratorForm
        raise PermissionDenied

    def get_queryset(self):
        """Ограничиваем доступ только к своим товарам или для модераторов."""
        if self.request.user.has_perm("catalog.can_unpublish_product"):
            return Product.objects.all()
        return Product.objects.filter(owner=self.request.user)


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = "catalog/product_detail.html"


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = "catalog/product_delete.html"
    success_url = reverse_lazy("catalog:product_list")

    def get_queryset(self):
        """Ограничиваем доступ к удалению только владельцу или модератору."""
        if self.request.user.has_perm("catalog.delete_product"):
            return Product.objects.all()
        return Product.objects.filter(owner=self.request.user)


class ContactsView(LoginRequiredMixin, TemplateView):
    template_name = "catalog/contacts.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["contacts"] = Contact.objects.all()
        context["latest_products"] = Product.objects.all().order_by("-created_at")[:5]
        return context

    def post(self, request, *args, **kwargs):
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message = request.POST.get("message")

        if name and phone and message:
            Contact.objects.create(name=name, phone=phone, message=message)

        return redirect("catalog:contacts")

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <!-- Подключите статичеcкие файлы со стилями Bootstrap -->
    {% load static %}
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">

</head>
<body>
{% include 'catalog/header.html' %}



<div class="container">
{% block content %}
{% endblock %}

{% include 'catalog/footer.html' %}

</div>
<!-- Подключите статичеcкие файлы со скриптами Bootstrap -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <!-- Контактные данные -->
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h2>Контактные данные</h2>
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond, WA, 98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>

        <!-- Связь с нами -->
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message" class="form-control" id="message" placeholder="Ваше сообщение"
                                      required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Список последних 5 продуктов -->
    <div class="row text-start">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h2>Контактные данные</h2>
                    <ul>
                        {% for contact in contacts %}
                        <li>{{ contact.name }} - {{ contact.email }} - {{ contact.phone }}</li>
                        {% endfor %}
                    </ul>

                    <h2>Последние 5 продуктов</h2>
                    <ul>
                        {% for product in latest_products %}
                        <li>{{ product.name }} - {{ product.created_at }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2025</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'catalog:contacts' %}/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

catalog/templates/catalog/header.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_list' %}">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_create' %}">Добавить товар</a>
    </nav>
    {% if user.is_authenticated %}
    <nav class="ms-auto">
        <form action="{% url 'users:logout' %}" method="post" class="d-inline">
            {% csrf_token %}
            <button type="submit" class="p-2 btn btn-outline-primary">Выход</button>
        </form>
    </nav>
    {% else %}
    <nav class="ms-auto">
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Вход</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
    </nav>
    {% endif %}
</div>

catalog/templates/catalog/product_card.html
{% load my_tags %}

<div class="col-md-3 d-flex align-items-stretch">
    <div class="card mb-4 box-shadow">
        <div class="card-header text-center">
            <h4 class="my-0 font-weight-normal">{{ product.name|truncatechars:40 }}</h4>
        </div>
        <div class="card-body d-flex flex-column align-items-center">
            <div class="text-center mb-3">
                <img src="{{ product.image|media_filter }}" alt="{{ product.name }}" class="img-fluid" style="max-width: 70%;">
            </div>
            <ul class="list-unstyled mt-3 mb-4 text-start flex-grow-1">
                <li>{{ product.description|truncatewords:20 }}</li>
            </ul>
            <a class="btn btn-primary" href="{% url 'catalog:product_detail' product.pk %}">Подробнее</a>
        </div>
    </div>
</div>

catalog/templates/catalog/product_category_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>
<div class="container">
    <div class="row text-center">
        {% for category in categories %}
        <div class="col-md-3 d-flex align-items-stretch">
            <div class="card mb-4 box-shadow">
                <div class="card-header text-center">
                    <h4 class="my-0 font-weight-normal">{{ category.name|truncatechars:40 }}</h4>
                </div>
                <div class="card-body d-flex flex-column align-items-center">
                    <div class="text-center mb-3">
                        <img src="{{ category.image|media_filter }}" alt="{{ category.name }}" class="img-fluid"
                             style="max-width: 70%;">
                    </div>
                    <ul class="list-unstyled mt-3 mb-4 text-start flex-grow-1">
                        <li>{{ category.description|truncatewords:20 }}</li>
                    </ul>
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                       href="{% url 'catalog:product_detail' category.id %}">Посмотреть</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_delete.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {% if perms.catalog.delete_product or request.user == object.owner %}
        <h2>Вы действительно хотите удалить товар {{ product.name }}?</h2>
        <button type="submit" class="btn btn-danger">Подтвердить удаление</button>
    {% endif %}
    <a href="{% url 'catalog:product_list' %}" class="btn btn-secondary">Отмена</a>
</form>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card mb-4 shadow-sm">
                <div class="card-header text-center">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body text-center">
                    <img src="{{ object.image|media_filter }}" class="img-fluid" style="max-width: 400px;">
                    <h3 class="mt-3">Цена:</h3>
                    <h3 class="text-primary">{{ object.price }} рублей</h3>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card p-3 shadow-sm">
                <p class="text-start">{{ object.description }}</p>
            </div>
            <div class="text-center mt-3">
                {% if request.user == object.owner or perms.catalog.can_unpublish_product %}
                    <a class="btn btn-success" href="{% url 'catalog:update_product' product.pk %}">Редактировать</a>
                {% endif %}
                {% if perms.catalog.delete_product or request.user == object.owner %}
                    <a class="btn btn-danger" href="{% url 'catalog:product_delete' product.pk %}">Удалить</a>
                {% endif %}
                <a class="btn btn-primary" href="{% url 'catalog:product_list' %}">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>
<div class="row justify-content-center text-center">
    {% for product in product_list %}
        {% if product.status or perms.catalog.can_unpublish_product %}
        {% include 'catalog/product_card.html' %}
        {% endif %}
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product_update.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<h1>Добавление продукта</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.as_p }}
    {% if object %}
        <button type="submit" class="btn btn-primary mt-3">Сохранить</button>
    {% else %}
        <button type="submit" class="btn btn-primary mt-3">Добавить</button>
    {% endif %}
</form>
{% endblock %}